java_library(
    name = "everything",
    srcs = glob(["src/**/*.java"]),
    deps = [
      "@maven//:org_swevolution_add_Add",
      "@maven//:org_swevolution_subtract_Subtract",
      "@maven//:org_swevolution_multiply_Multiply",
      "@maven//:org_swevolution_divide_Divide",
    ],
)
