java_binary(
    name = "Calculator",
    srcs = glob(["src/**/*.java"]),
    main_class = "Calculator",
    deps = [
      "@maven//:org_swevolution_Add_Add",
      "@maven//:org_swevolution_subtract_Subtract",
      "@maven//:org_swevolution_multiply_Multiply",
      "@maven//:org_swevolution_divide_Divide",
    ]
)
