load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "2.8"
RULES_JVM_EXTERNAL_SHA = "79c9850690d7614ecdb72d68394f994fef7534b292c4867ce5e7dec0aa7bdfad"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "org.swevolution.add:Add:1.0-SNAPSHOT",
        "org.swevolution.subtract:Subtract:1.0-SNAPSHOT",
        "org.swevolution.multiply:Multiply:1.0-SNAPSHOT",
        "org.swevolution.divide:Divide:1.0-SNAPSHOT"
    ],
    repositories = [
        "file://C:/Users/dfbra/.m2/repository/"
    ],
)
